CC = clang++-9 -std=c++2a

all: Q1 Q2 Q3 Q4 Q5 Q6

Q1: Q1.cpp
	$(CC) Q1.cpp -o Q1
Q2: 
	echo write ./Q2.sh to run Q2.
Q3: Q3.cpp
	$(CC) Q3.cpp -o Q3
Q4: Q4.cpp
	$(CC) Q4.cpp -o Q4
Q5: Q5.cpp
	$(CC) Q5.cpp -o Q5
Q6: Q6.cpp
	$(CC) Q6.cpp -o Q6
Q7: Q7.cpp
	$(CC) Q7.cpp -o Q7

clean:
	rm -f Q1 Q2 Q3 Q4 Q5 Q6 Q7 a.out