CC = clang++-9 -std=c++2a

all: Q1 Q2 Q3 Q4 Q5 Q6 Q7

Q1: Q1.cpp
	$(CC) Q1.cpp -o Q1
Q2: 
	echo Q2 was not implemented
Q3: 
	echo Q3 was not implemented
Q4: 
	echo Q4 is implemented in a bash file Q4.sh
Q5: Q5.cpp
	$(CC) Q5.cpp -o Q5
Q6: Q6.cpp
	$(CC) Q6.cpp -o Q6

clean:
	rm -f Q1 Q2 Q3 Q4 Q5 Q6 Q7 a.out *.txt